/*
 * This file is generated by jOOQ.
 */
package com.tosin.chatter;


import com.tosin.chatter.tables.Users;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_EMAIL_INDEX = Internal.createIndex(DSL.name("users_email_index"), Users.USERS, new OrderField[] { Users.USERS.EMAIL }, false);
    public static final Index USERS_USERNAME_INDEX = Internal.createIndex(DSL.name("users_username_index"), Users.USERS, new OrderField[] { Users.USERS.USERNAME }, false);
}
